# Generated by Django 3.2.16 on 2023-02-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'MY Priority',
            },
        ),
        migrations.CreateModel(
            name='MyTofI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'MY Types of Intervention',
            },
        ),
        migrations.CreateModel(
            name='MySOinP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=500, null=True)),
                ('intervention_type', models.ManyToManyField(blank=True, related_name='specific_objective_in_priority', to='blog.MyTofI', verbose_name='Type of Intervention')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_objective_in_priority', to='blog.mypriority')),
            ],
            options={
                'verbose_name_plural': 'MY SOinP',
            },
        ),
        migrations.AddField(
            model_name='mypriority',
            name='intervention_type',
            field=models.ManyToManyField(blank=True, related_name='priorities', to='blog.MyTofI', verbose_name='Type of Intervention'),
        ),
    ]
